main:
  name: "trackd"
  version: "1.0.0"
  base_path: 'cwd'
  log:
    path: "/log/witp/trackd"
    name: "main"
    verbose: False
    level: "DEBUG"
thread_enable:
  dev: false #enable device thread, serial connection for autostar
  rmq: false # enable RabbitMQ Control Thread
  cli: true # enable the Command Line Interface Thread
dev:
  name: "DeviceThread" #thread name
  type: "ETX-90" #thread name
  protocol: "autostar" #device protocol
  connection:
    type: "serial" #Connection Type: TCP, UDP, Serial
    port: /dev/ttyUSB0 #port of tracker
    baud: 9600
    startup_delay: 1 #thread initialization delay
    retry_time: 5 #rate in seconds to attempt device reconnection
    timeout: 0.001 #Connection Timeout Window
    poll_rate: 1 #Rate at which to query tracker for feedback and status
    update_rate: 0.25 #Rate at which to send commands to tracker
cli:
  name: 'CLI_Thread'
  msgs:
    base_path: "cwd"
    path: "config"
    file: "track_cmds.yaml"
rmq: #RabbitMQ based control
  name: "RMQ Service"
  protocol: "RMQ" #indicates the connection thread for the service uses RabbitMQ
  connection: #Passed to the BrokerConnector class for RMQ Connections
    type: 'daemon' #Opetions: daemon or client
    ip: "0.0.0.0" #Ip Address of RabbitMQ Broker
    port: 5672  #default IP of RabbitMQ
    user: "guest"
    pass: "guest"
    vhost: "witp"
    exchange: "track"
    exchange_key: "track"
    produce_key: "tm" #Daemons Produce Telemetry
    consume_key: "tc" #Daemons Consume Telecommands
    exch_type: "topic"
    durable: True
    retry_wait: 5
    update_delay: 0.1
    app_id: "trackd"
