main:
  name: "trackd"
  version: "1.0.0"
  base_path: 'cwd'
  log:
    path: "/log/witp/trackd"
    name: "main"
    verbose: True
    level: "DEBUG"
  observer:
    lat: 37.1548050
    lon: -80.5674639
    alt: 572
thread_enable:
  dev: false #enable device thread, serial connection for autostar
  rmq: false # enable RabbitMQ Control Thread
  cli: false # enable the Command Line Interface Thread
  gui: true # enable the Command Line Interface Thread
  sbs1: true # enable the SBS1 ADSB Client Thread
  mlat: false # enable the SBS1 ADSB Client Thread
dev:
  name: "DeviceThread" #thread name
  type: "ETX-90" #thread name
  protocol: "autostar" #device protocol
  connection:
    type: "serial" #Connection Type: TCP, UDP, Serial
    port: '/dev/ttyUSB0' #port of tracker
    baud: 9600
    startup_delay: 1 #thread initialization delay
    retry_time: 5 #rate in seconds to attempt device reconnection
    timeout: 0.001 #Connection Timeout Window
    poll_rate: 1 #Rate at which to query tracker for feedback and status
    update_rate: 0.25 #Rate at which to send commands to tracker
gui:
  name: 'GUI_Thread'
  title: "Autostar (ETX-60/70/90) Control GUI, v1.0.0"
  update_rate: 0.5
  azimuth:
    home: 180.0
    min: 0.0
    max: 360.0
    rate_min: -10.0
    rate_max: 10.0
    rate_dial: false
  elevation:
    home: 0.0
    min: -5.0
    max: 95
    rate_min: -5.0
    rate_max: 5.0
    rate_dial: false
  focuser:
    name: "Focuser Control"
  joystick:
    name: "Slew Control"
    az_rate_lim: 255
    el_rate_lim: 255
  con:
    name: "Autostar Connection"
    type: "serial"
    port: '/dev/ttyUSB0'
    baud: 9600
  adsb:
    name: "ADSB Connection"
    ip: '10.1.2.10'
    sbs1_port: 30003
    mlat_port: 30106
  observer:
    name: "Observer Location"
    lat: 37.1548050
    lon: -80.5674639
    alt: 572
sbs1:
  name: "adsb" #thread name
  type: "sbs1" #type of device
  connection:
    type: "tcp" #Connection Type: TCP, UDP, Serial
    ip: "10.1.2.10" #IP of dump1090
    port: 30003 #SBS1 (CSV) dump1090 port
    startup_delay: 1 #thread initialization delay
    retry_time: 5 #rate in seconds to attempt device reconnection
    watchdog_time: 10 #rate in seconds to attempt device reconnection
    timeout: 0.001 #Connection Timeout Window
mlat:
  name: "adsb" #thread name
  type: "mlat" #type of device
  connection:
    type: "tcp" #Connection Type: TCP, UDP, Serial
    ip: "10.1.2.10" #IP of dump1090
    port: 30106 #MLAT (CSV) dump1090 port
    startup_delay: 1 #thread initialization delay
    retry_time: 10 #rate in seconds to attempt device reconnection
    watchdog_time: 60 #rate in seconds to attempt device reconnection
    timeout: 0.001 #Connection Timeout Window
cli:
  name: 'CLI_Thread'
  msgs:
    base_path: "cwd"
    path: "config"
    file: "track_cmds.yaml"
rmq: #RabbitMQ based control
  name: "RMQ Service"
  protocol: "RMQ" #indicates the connection thread for the service uses RabbitMQ
  connection: #Passed to the BrokerConnector class for RMQ Connections
    type: 'daemon' #Opetions: daemon or client
    ip: "0.0.0.0" #Ip Address of RabbitMQ Broker
    port: 5672  #default IP of RabbitMQ
    user: "guest"
    pass: "guest"
    vhost: "witp"
    exchange: "track"
    exchange_key: "track"
    produce_key: "tm" #Daemons Produce Telemetry
    consume_key: "tc" #Daemons Consume Telecommands
    exch_type: "topic"
    durable: True
    retry_wait: 5
    update_delay: 0.1
    app_id: "trackd"
